# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19d29cf83ea94c60af5467cad01a330811389ccc6bc8e43a32557c6cfeeeeb48e981936f974e3290b38600198dd526b6e53e6f6449b1faaecd0620e583ba746

test:
  secret_key_base: 90f85342de07c7023842f8f8656983b68f9ccc8ec3b849069bc81d8e80af00878de1f8047e46cb7e0f476af94632f8b396860a0bebd316b8d37098a488fcdb19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
